<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>LayoutGuard</AssemblyName>
    <RootNamespace>LayoutGuard.Windows</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.2.4</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LayoutGuard.Core/LayoutGuard.Core.csproj" />
    <PackageReference Include="Interop.UIAutomationClient" Version="10.19041.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="LayoutGuard.Windows.Checks" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
</Project>
